version: '3'

services:
    app:
        build: .
        container_name: app
        #entrypoint: dockerize -template .docker/app/.env:.env -wait tcp://mysql:3306 -timeout 60s ./.docker/entrypoint.sh
        #environment:
        #    - DB_HOST=mysql
        #    - DB_DATABASE=laravel
        #    - DB_USERNAME=root
        #    - DB_PASSWORD=root
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on: 
            - mysql
            - redis


    nginx:
        build: .docker/nginx
        container_name: nginx
        entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf.template:/etc/nginx/conf.d/nginx.conf nginx -g 'daemon off;'
        environment:
            - APP_HOST=app
            - APP_PORT=9000
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes: 
            - .:/var/www
        networks:
            - app-network
        depends_on: 
            - app


    mysql:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/mysqldata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network


    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network


networks:
    app-network:
        driver: bridge